const DEFAULT_TIMER_IN_SECOND = 5;
const DEFAULT_TIMER_IN_STRING = "00:05";
const START_SECOND = 0;
const COUNTDOWN_STEP = 1;
const ONE_SECOND_IN_MS = 1000;

export {
  DEFAULT_TIMER_IN_SECOND,
  DEFAULT_TIMER_IN_STRING,
  START_SECOND,
  COUNTDOWN_STEP,
  ONE_SECOND_IN_MS,
};
