const DEFAULT_SCORE = 0;
const CORRECT_POINT = 10;
const START_QUESTION_NUMBER = 1;
const QUESTION_STEP = 1;
const NO_ANSWERED = 0;
const START_QUESTION_INDEX = 0;

export {
  DEFAULT_SCORE,
  CORRECT_POINT,
  START_QUESTION_NUMBER,
  QUESTION_STEP,
  NO_ANSWERED,
  START_QUESTION_INDEX,
};
